### ISSUE TITLE
How to catch file not found?

### ISSUE THREAD

**Issue by cristianvasquez** [rdf-ext/rdf-utils-fs#8]
The following snippet:

```js
const { createReadStream } = require('fs')
createReadStream('something.ttl')
```

Throws the unhandled error:
```
 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'IdoNotExist.ttl'
}
```

Whereas 

```
const { fromFile } = require('rdf-utils-fs')
fromFile('IdoNotExist.ttl')
```

Do not throw an error.

The stream object is returned synchronously, and the file opens asynchronously. The error is not thrown.

I think it's related to: https://github.com/zazuko/barnard59/issues/62

**Comment by bergos** [comment]
The stream should emit a file not found error. The problem mentioned in the barnard59 issue was probably a bug in barnard59-core. I left a comment in the other issue. Please try to update the dependencies and check if the error is still there.

**Comment by cristianvasquez** [comment]
Sorry, I did not see this message. 

After updating dependencies the error is gone
